//
//  HookInstaller.swift
//  ClaudeIsland
//
//  Auto-installs Claude Code hooks on app launch
//

import Foundation
import os.log

private let installerLogger = Logger(subsystem: "com.claudeisland", category: "HookInstaller")

struct HookInstaller {

    private static let wrapperRelPath = "hooks/ccmonitor-statusline-wrapper.sh"
    /// Path as written into settings.json (tilde-expanded by the shell at statusline invocation)
    private static let wrapperSettingsPath = "~/.claude/\(wrapperRelPath)"

    /// Install hook script and update settings.json on app launch
    static func installIfNeeded() {
        let claudeDir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".claude")
        let hooksDir = claudeDir.appendingPathComponent("hooks")
        let pythonScript = hooksDir.appendingPathComponent("claude-island-state.py")
        let settings = claudeDir.appendingPathComponent("settings.json")

        try? FileManager.default.createDirectory(
            at: hooksDir,
            withIntermediateDirectories: true
        )

        if let bundled = Bundle.main.url(forResource: "claude-island-state", withExtension: "py") {
            try? FileManager.default.removeItem(at: pythonScript)
            try? FileManager.default.copyItem(at: bundled, to: pythonScript)
            try? FileManager.default.setAttributes(
                [.posixPermissions: 0o755],
                ofItemAtPath: pythonScript.path
            )
        }

        installStatuslineScripts(hooksDir: hooksDir)

        updateSettings(at: settings, claudeDir: claudeDir)
    }

    /// Copy ccmonitor-statusline.py + bridge_send.py from the bundle and write the wrapper shim.
    /// The wrapper captures rate_limits for the battery bar while preserving any user-configured prompt.
    private static func installStatuslineScripts(hooksDir: URL) {
        let scripts: [(resource: String, ext: String, filename: String, executable: Bool)] = [
            ("ccmonitor-statusline", "py", "ccmonitor-statusline.py", true),
            ("bridge_send",          "py", "bridge_send.py",          false),
        ]

        for script in scripts {
            guard let bundled = Bundle.main.url(forResource: script.resource, withExtension: script.ext) else {
                installerLogger.error("Missing bundled resource: \(script.filename, privacy: .public)")
                continue
            }
            let dest = hooksDir.appendingPathComponent(script.filename)
            try? FileManager.default.removeItem(at: dest)
            try? FileManager.default.copyItem(at: bundled, to: dest)
            if script.executable {
                try? FileManager.default.setAttributes(
                    [.posixPermissions: 0o755],
                    ofItemAtPath: dest.path
                )
            }
        }

        let wrapperPath = hooksDir.appendingPathComponent("ccmonitor-statusline-wrapper.sh")
        let wrapperBody = """
        #!/usr/bin/env bash
        # Auto-generated by claude-island. Do not edit — this file is overwritten on each launch.
        # To customize the displayed prompt, edit ~/.claude/statusline-original.sh.
        input=$(cat)
        # Fire-and-forget usage extraction; never block prompt rendering.
        printf '%s' "$input" | python3 ~/.claude/hooks/ccmonitor-statusline.py >/dev/null 2>&1 &
        # Delegate to preserved original statusline, if any.
        if [ -x ~/.claude/statusline-original.sh ]; then
            printf '%s' "$input" | bash ~/.claude/statusline-original.sh
        fi

        """
        try? wrapperBody.write(to: wrapperPath, atomically: true, encoding: .utf8)
        try? FileManager.default.setAttributes(
            [.posixPermissions: 0o755],
            ofItemAtPath: wrapperPath.path
        )
    }

    /// If the user has a prior non-wrapper `.statusLine.command`, preserve it to a file the wrapper can exec.
    /// Returns the new command to install (wrapper path), or nil if already our wrapper.
    private static func preserveExistingStatusline(
        currentCommand: String?,
        claudeDir: URL
    ) -> String? {
        // Already our wrapper — nothing to do.
        if let cmd = currentCommand, cmd.contains("ccmonitor-statusline-wrapper.sh") {
            return nil
        }

        // Preserve prior command (if any) as an executable bash script.
        if let cmd = currentCommand, !cmd.isEmpty {
            let originalPath = claudeDir.appendingPathComponent("statusline-original.sh")
            if !FileManager.default.fileExists(atPath: originalPath.path) {
                let body = "#!/usr/bin/env bash\n\(cmd)\n"
                do {
                    try body.write(to: originalPath, atomically: true, encoding: .utf8)
                    try FileManager.default.setAttributes(
                        [.posixPermissions: 0o755],
                        ofItemAtPath: originalPath.path
                    )
                    installerLogger.info("Preserved original statusLine to ~/.claude/statusline-original.sh")
                } catch {
                    installerLogger.error("Failed to preserve original statusLine: \(error.localizedDescription, privacy: .public)")
                }
            }
        }

        return wrapperSettingsPath
    }

    private static func updateSettings(at settingsURL: URL, claudeDir: URL) {
        var json: [String: Any] = [:]
        if let data = try? Data(contentsOf: settingsURL),
           let existing = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            json = existing
        }

        // statusLine: preserve any existing user command to statusline-original.sh, then
        // point .statusLine at our wrapper.
        let existingCommand = (json["statusLine"] as? [String: Any])?["command"] as? String
        if let newCommand = preserveExistingStatusline(currentCommand: existingCommand, claudeDir: claudeDir) {
            json["statusLine"] = ["type": "command", "command": newCommand]
        }

        let python = detectPython()
        let command = "\(python) ~/.claude/hooks/claude-island-state.py"
        let hookEntry: [[String: Any]] = [["type": "command", "command": command]]
        let hookEntryWithTimeout: [[String: Any]] = [["type": "command", "command": command, "timeout": 86400]]
        let withMatcher: [[String: Any]] = [["matcher": "*", "hooks": hookEntry]]
        let withMatcherAndTimeout: [[String: Any]] = [["matcher": "*", "hooks": hookEntryWithTimeout]]
        let withoutMatcher: [[String: Any]] = [["hooks": hookEntry]]
        let preCompactConfig: [[String: Any]] = [
            ["matcher": "auto", "hooks": hookEntry],
            ["matcher": "manual", "hooks": hookEntry]
        ]

        var hooks = json["hooks"] as? [String: Any] ?? [:]

        let hookEvents: [(String, [[String: Any]])] = [
            ("UserPromptSubmit", withoutMatcher),
            ("PreToolUse", withMatcher),
            ("PostToolUse", withMatcher),
            ("PermissionRequest", withMatcherAndTimeout),
            ("Notification", withMatcher),
            ("Stop", withoutMatcher),
            ("SubagentStop", withoutMatcher),
            ("SessionStart", withoutMatcher),
            ("SessionEnd", withoutMatcher),
            ("PreCompact", preCompactConfig),
        ]

        for (event, config) in hookEvents {
            if var existingEvent = hooks[event] as? [[String: Any]] {
                let hasOurHook = existingEvent.contains { entry in
                    if let entryHooks = entry["hooks"] as? [[String: Any]] {
                        return entryHooks.contains { h in
                            let cmd = h["command"] as? String ?? ""
                            return cmd.contains("claude-island-state.py")
                        }
                    }
                    return false
                }
                if !hasOurHook {
                    existingEvent.append(contentsOf: config)
                    hooks[event] = existingEvent
                }
            } else {
                hooks[event] = config
            }
        }

        json["hooks"] = hooks

        if let data = try? JSONSerialization.data(
            withJSONObject: json,
            options: [.prettyPrinted, .sortedKeys]
        ) {
            try? data.write(to: settingsURL)
        }
    }

    /// Check if hooks are currently installed
    static func isInstalled() -> Bool {
        let claudeDir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".claude")
        let settings = claudeDir.appendingPathComponent("settings.json")

        guard let data = try? Data(contentsOf: settings),
              let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let hooks = json["hooks"] as? [String: Any] else {
            return false
        }

        for (_, value) in hooks {
            if let entries = value as? [[String: Any]] {
                for entry in entries {
                    if let entryHooks = entry["hooks"] as? [[String: Any]] {
                        for hook in entryHooks {
                            if let cmd = hook["command"] as? String,
                               cmd.contains("claude-island-state.py") {
                                return true
                            }
                        }
                    }
                }
            }
        }
        return false
    }

    /// Uninstall hooks from settings.json and remove script
    static func uninstall() {
        let claudeDir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".claude")
        let hooksDir = claudeDir.appendingPathComponent("hooks")
        let pythonScript = hooksDir.appendingPathComponent("claude-island-state.py")
        let settings = claudeDir.appendingPathComponent("settings.json")

        try? FileManager.default.removeItem(at: pythonScript)

        guard let data = try? Data(contentsOf: settings),
              var json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              var hooks = json["hooks"] as? [String: Any] else {
            return
        }

        for (event, value) in hooks {
            if var entries = value as? [[String: Any]] {
                entries.removeAll { entry in
                    if let entryHooks = entry["hooks"] as? [[String: Any]] {
                        return entryHooks.contains { hook in
                            let cmd = hook["command"] as? String ?? ""
                            return cmd.contains("claude-island-state.py")
                        }
                    }
                    return false
                }

                if entries.isEmpty {
                    hooks.removeValue(forKey: event)
                } else {
                    hooks[event] = entries
                }
            }
        }

        if hooks.isEmpty {
            json.removeValue(forKey: "hooks")
        } else {
            json["hooks"] = hooks
        }

        if let data = try? JSONSerialization.data(
            withJSONObject: json,
            options: [.prettyPrinted, .sortedKeys]
        ) {
            try? data.write(to: settings)
        }
    }

    private static func detectPython() -> String {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/which")
        process.arguments = ["python3"]
        process.standardOutput = FileHandle.nullDevice
        process.standardError = FileHandle.nullDevice

        do {
            try process.run()
            process.waitUntilExit()
            if process.terminationStatus == 0 {
                return "python3"
            }
        } catch {}

        return "python"
    }
}
